# Generated by Django 2.0.6 on 2020-10-22 02:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('theme', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TEST',
        ),
        migrations.DeleteModel(
            name='TinTucAll',
        ),
    ]
