# Generated by Django 3.0.5 on 2020-09-23 07:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('theme', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TEST',
        ),
        migrations.DeleteModel(
            name='TinTucAll',
        ),
    ]
