# Generated by Django 3.0.5 on 2020-10-22 06:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('theme', '0002_auto_20201022_0927'),
        ('theme', '0002_auto_20200923_0722'),
    ]

    operations = [
    ]
